service: knex-serverless
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  createUser:
    handler: functions/createUser.handler
    events:
      - http:
          method: POST
          path: /user
          cors: true
  getUsers:
    handler: functions/getUsers.handler
    events:
      - http:
          method: GET
          path: /users
